name: deploy order service to AWS Fargate

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
  workflow_dispatch: # to manually run workflow
    
jobs:
  build-app:
    runs-on:
      ubuntu-latest
    steps:
      - name: step-1 
        uses: actions/checkout@v3
      
      - name: step 2
        env:
          name: prawin
        run: | 
          echo Hello World!!!
          echo Hello ${{ env.name }}
          echo "colour=yellow" >> $GITHUB_ENV
          
      - name: step 3 run multiline script
        run: |
          echo line 1
          echo line 2
          echo ${{ env.colour }}
  
    
 