name: deploy order service to AWS Fargate

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
  workflow_dispatch: # to manually run workflow
    
jobs:
  provision-infra:
    runs-on:
      ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: find environment
        run: |
          if [ ${{ github.ref }} == 'refs/heads/master' ]; then
          echo "environment=arn:aws:iam::183295410578:role/github-actions-cloudformation-deploy-role" >> $GITHUB_ENV
          elif [ ${{ github.ref }} == 'refs/heads/dev' ]; then
          echo "environment=arn:aws:iam::123:role/github-actions-cloudformation-deploy-role" >> $GITHUB_ENV
          echo Environment $ {{ env.environment }}
          fi
      
      - name: configure AWS credentials
        id: credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.environment}}
          role-session-name: DeployInfra
          aws-region: us-east-1
          
      - name: get account id
        run: |
          echo ${{ steps.credentials.outputs.aws-account-id }}
          
      - name: deploy infra
        id: infra
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: $ {{ env.environment }}-infra
          template: ./cftemplates/infra.yml
          role-arn: arn:aws:iam::${{ steps.credentials.outputs.aws-account-id }}:role/github-actions-cloudformation-stack-role
          no-fail-on-empty-changeset: "1"